# 1. 기본적인 DNN

# 2. 사이킷런(sklearn) 이용
- 원핫인코딩을 하지 않고 라벨인코딩까지만 해야 작동. 원핫인코딩은 작동되지 않음

In [1]:
from sklearn import datasets # iris 데이터
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier

In [5]:
# 1. 데이터
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target
print(iris_X[::50], iris_y[::50])
train_X, test_X, train_y, test_y = train_test_split(iris_X, iris_y,
                                                    test_size=0.1, # 기본값은 train:test = 0.75:0.25
                                                    random_state=4,
                                                    stratify=iris_y
                                                   )
print(train_X.shape, train_y.shape, test_X.shape, test_y.shape)

[[5.1 3.5 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.3 3.3 6.  2.5]] [0 1 2]
(135, 4) (135,) (15, 4) (15,)


In [31]:
# 사이킷런에서 제공하는 다층퍼셉트론 기반의 분류 알고리즘 api
mlp = MLPClassifier(hidden_layer_sizes=(60, 128, 50,30),
                    activation='relu',
                    solver='adam', # optimizer 설정값
                    max_iter=1000, # 최대학습횟수
                    early_stopping=True, # 조기 종료 활성화
                    n_iter_no_change=10, # 검증셋 손실함수가 개선되지 않으면 조기종료
                    validation_fraction=0.1 # 검증셋 비율
                   )

In [32]:
mlp.fit(train_X, train_y)

MLPClassifier(early_stopping=True, hidden_layer_sizes=(60, 128, 50, 30),
              max_iter=1000)

In [33]:
mlp.score(test_X, test_y)

0.8

In [34]:
mlp.predict(test_X[0:1])

array([0])

# 3. 클래스 생성

In [65]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from tensorflow.keras.callbacks import EarlyStopping
import matplotlib.pyplot as plt
import numpy as np

In [55]:
class DNNClassifier:
    @staticmethod
    def build(input_dim=4, activation='relu', output_dim=3):
#         model = Sequential()
#         model.add(Input(input_dim,))
#         model.add(Dense(50, activation=activation))
#         model.add(Dense(50, activation=activation))
#         model.add(Dense(output_dim, activation='softmax'))
        model = Sequential([
            Input(input_dim,),
            Dense(50, activation=activation),
            Dense(30, activation=activation),
            Dense(output_dim, activation='softmax'),
        ])
        # 학습 과정 설정
        model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
        return model

In [61]:
# 1. 데이터 생성 및 전처리
# iris_Y = pd.get_dummies(iris_y).to_numpy()
# train_X, test_X, train_Y, test_Y = train_test_split(iris_X, iris_Y,
#                                                     test_size=0.1, # 기본값은 train:test = 0.75:0.25
#                                                     random_state=4,
#                                                     stratify=iris_y
#                                                    )
# print(train_X.shape, train_Y.shape, test_X.shape, test_Y.shape)
train_Y = pd.get_dummies(train_y).values
test_Y = pd.get_dummies(test_y).values
# 2. 모델
model = DNNClassifier.build(input_dim=4,
                            activation='relu',
                            output_dim=3)
# 3. 모델 학습
earlystopping = EarlyStopping(patience=150)
hist = model.fit(train_X, train_Y,
                 epochs=1000,
                 validation_split=0.1,
                 callbacks=[earlystopping]
                )

Epoch 1/1000
4/4 [==============================] - 1s 95ms/step - loss: 1.0394 - accuracy: 0.4876 - val_loss: 0.7139 - val_accuracy: 0.9286
Epoch 2/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.8143 - accuracy: 0.6777 - val_loss: 0.7175 - val_accuracy: 0.7857
Epoch 3/1000
4/4 [==============================] - 0s 18ms/step - loss: 0.7468 - accuracy: 0.6529 - val_loss: 0.6910 - val_accuracy: 0.7857
Epoch 4/1000
4/4 [==============================] - 0s 15ms/step - loss: 0.7058 - accuracy: 0.6529 - val_loss: 0.6207 - val_accuracy: 0.7857
Epoch 5/1000
4/4 [==============================] - 0s 19ms/step - loss: 0.6613 - accuracy: 0.6529 - val_loss: 0.5352 - val_accuracy: 0.7857
Epoch 6/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.6247 - accuracy: 0.7438 - val_loss: 0.4695 - val_accuracy: 0.7857
Epoch 7/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.5991 - accuracy: 0.8347 - val_loss: 0.4316 - val_accuracy: 0.7857
Epoch 8/1000


Epoch 59/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.1412 - accuracy: 0.9835 - val_loss: 0.1329 - val_accuracy: 0.9286
Epoch 60/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.1369 - accuracy: 0.9835 - val_loss: 0.1228 - val_accuracy: 1.0000
Epoch 61/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.1304 - accuracy: 0.9835 - val_loss: 0.1240 - val_accuracy: 1.0000
Epoch 62/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.1265 - accuracy: 0.9835 - val_loss: 0.1282 - val_accuracy: 0.9286
Epoch 63/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.1246 - accuracy: 0.9835 - val_loss: 0.1232 - val_accuracy: 1.0000
Epoch 64/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.1219 - accuracy: 0.9835 - val_loss: 0.1197 - val_accuracy: 1.0000
Epoch 65/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.1195 - accuracy: 0.9835 - val_loss: 0.1192 - val_accuracy: 1.0000
Epoch 

4/4 [==============================] - 0s 12ms/step - loss: 0.0707 - accuracy: 0.9835 - val_loss: 0.1071 - val_accuracy: 0.9286
Epoch 117/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0718 - accuracy: 0.9835 - val_loss: 0.1044 - val_accuracy: 0.9286
Epoch 118/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0696 - accuracy: 0.9835 - val_loss: 0.1070 - val_accuracy: 0.9286
Epoch 119/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0703 - accuracy: 0.9835 - val_loss: 0.1099 - val_accuracy: 0.9286
Epoch 120/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0733 - accuracy: 0.9835 - val_loss: 0.1045 - val_accuracy: 0.9286
Epoch 121/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0682 - accuracy: 0.9917 - val_loss: 0.1055 - val_accuracy: 0.9286
Epoch 122/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0659 - accuracy: 0.9835 - val_loss: 0.1119 - val_accuracy: 0.9286
Epoch 123/1000

4/4 [==============================] - 0s 12ms/step - loss: 0.0550 - accuracy: 0.9917 - val_loss: 0.1122 - val_accuracy: 0.9286
Epoch 174/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0543 - accuracy: 0.9917 - val_loss: 0.1111 - val_accuracy: 0.8571
Epoch 175/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0554 - accuracy: 0.9917 - val_loss: 0.1111 - val_accuracy: 0.8571
Epoch 176/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.0547 - accuracy: 0.9917 - val_loss: 0.1126 - val_accuracy: 0.9286
Epoch 177/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0544 - accuracy: 0.9917 - val_loss: 0.1133 - val_accuracy: 0.9286
Epoch 178/1000
4/4 [==============================] - 0s 13ms/step - loss: 0.0589 - accuracy: 0.9917 - val_loss: 0.1185 - val_accuracy: 0.9286
Epoch 179/1000
4/4 [==============================] - 0s 14ms/step - loss: 0.0526 - accuracy: 0.9917 - val_loss: 0.1118 - val_accuracy: 0.8571
Epoch 180/1000

4/4 [==============================] - 0s 12ms/step - loss: 0.0467 - accuracy: 0.9917 - val_loss: 0.1247 - val_accuracy: 0.9286
Epoch 231/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0489 - accuracy: 0.9917 - val_loss: 0.1289 - val_accuracy: 0.9286
Epoch 232/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0510 - accuracy: 0.9917 - val_loss: 0.1234 - val_accuracy: 0.9286
Epoch 233/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0484 - accuracy: 0.9917 - val_loss: 0.1213 - val_accuracy: 0.8571
Epoch 234/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0495 - accuracy: 0.9917 - val_loss: 0.1217 - val_accuracy: 0.8571
Epoch 235/1000
4/4 [==============================] - 0s 11ms/step - loss: 0.0495 - accuracy: 0.9917 - val_loss: 0.1236 - val_accuracy: 0.9286
Epoch 236/1000
4/4 [==============================] - 0s 12ms/step - loss: 0.0480 - accuracy: 0.9917 - val_loss: 0.1225 - val_accuracy: 0.8571
Epoch 237/1000

In [62]:
loss, accuracy = model.evaluate(test_X, test_Y)
print(f'정확도 : {accuracy*100}%')

1/1 [==============================] - 0s 29ms/step - loss: 0.0382 - accuracy: 1.0000
정확도 : 100.0%


In [66]:
np.argmax(model.predict(test_X[0].reshape(1,-1)))

1/1 [==============================] - 0s 28ms/step


0

# 4. 병렬처리

In [77]:
from tensorflow.keras.layers import concatenate
from tensorflow.keras import Model

In [78]:
train_X.shape, train_Y.shape, test_X.shape, test_Y.shape

((135, 4), (135, 3), (15, 4), (15, 3))

In [80]:
# 모델
input_ = Input(shape=(4,))
dense1 = Dense(50, activation='relu')(input_)
dense2 = Dense(80, activation='relu')(input_)
dense3 = Dense(30, activation='relu')(input_)
x = concatenate([dense1,dense2,dense3])
# x = Dense(units=160, actiaviton='relu')(input_)의 병렬처리 구현
output = Dense(units=3, activation='softmax')(x)
model = Model(inputs=input_, outputs=output)
model.summary()

Model: "model_3"
__________________________________________________________________________________________________
 Layer (type)                   Output Shape         Param #     Connected to                     
 input_15 (InputLayer)          [(None, 4)]          0           []                               
                                                                                                  
 dense_42 (Dense)               (None, 50)           250         ['input_15[0][0]']               
                                                                                                  
 dense_43 (Dense)               (None, 80)           400         ['input_15[0][0]']               
                                                                                                  
 dense_44 (Dense)               (None, 30)           150         ['input_15[0][0]']               
                                                                                            

In [83]:
# 학습 정의(설정), 학습
model.compile(loss='categorical_crossentropy',
              optimizer = 'adam',
              metrics = ['accuracy']
             )
model.fit(train_X, train_Y,
          epochs=200,
          verbose=1
         )

Epoch 1/200
5/5 [==============================] - 1s 2ms/step - loss: 0.0595 - accuracy: 0.9852
Epoch 2/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0609 - accuracy: 0.9852
Epoch 3/200
5/5 [==============================] - 0s 3ms/step - loss: 0.0662 - accuracy: 0.9778
Epoch 4/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0606 - accuracy: 0.9778
Epoch 5/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0553 - accuracy: 0.9852
Epoch 6/200
5/5 [==============================] - 0s 3ms/step - loss: 0.0640 - accuracy: 0.9852
Epoch 7/200
5/5 [==============================] - 0s 3ms/step - loss: 0.0607 - accuracy: 0.9852
Epoch 8/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0578 - accuracy: 0.9852
Epoch 9/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0617 - accuracy: 0.9778
Epoch 10/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0564 - accuracy: 0.9852
Epoch 11/200
5/5 [===========

5/5 [==============================] - 0s 2ms/step - loss: 0.0630 - accuracy: 0.9852
Epoch 85/200
5/5 [==============================] - 0s 1ms/step - loss: 0.0597 - accuracy: 0.9852
Epoch 86/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0554 - accuracy: 0.9852
Epoch 87/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0560 - accuracy: 0.9852
Epoch 88/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0566 - accuracy: 0.9852
Epoch 89/200
5/5 [==============================] - 0s 1ms/step - loss: 0.0555 - accuracy: 0.9852
Epoch 90/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0596 - accuracy: 0.9852
Epoch 91/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0575 - accuracy: 0.9778
Epoch 92/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0615 - accuracy: 0.9852
Epoch 93/200
5/5 [==============================] - 0s 1ms/step - loss: 0.0594 - accuracy: 0.9852
Epoch 94/200
5/5 [===============

5/5 [==============================] - 0s 2ms/step - loss: 0.0548 - accuracy: 0.9852
Epoch 168/200
5/5 [==============================] - 0s 3ms/step - loss: 0.0559 - accuracy: 0.9852
Epoch 169/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0542 - accuracy: 0.9852
Epoch 170/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0541 - accuracy: 0.9852
Epoch 171/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0551 - accuracy: 0.9778
Epoch 172/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0553 - accuracy: 0.9778
Epoch 173/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0540 - accuracy: 0.9778
Epoch 174/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0542 - accuracy: 0.9852
Epoch 175/200
5/5 [==============================] - 0s 2ms/step - loss: 0.0543 - accuracy: 0.9852
Epoch 176/200
5/5 [==============================] - 0s 1ms/step - loss: 0.0544 - accuracy: 0.9852
Epoch 177/200
5/5 [=====

In [84]:
# 학습평가
loss, accuracy = model.evaluate(test_X, test_Y)
print(accuracy*100, '%')

1/1 [==============================] - 0s 185ms/step - loss: 0.0364 - accuracy: 1.0000
100.0 %
